default_config:

homeassistant:
  name: Home

  internal_url: !secret url
  external_url: !secret url

  latitude: !secret latitude
  longitude: !secret longitude

  time_zone: Europe/Kiev
  unit_system: metric

  packages:
    alexa: !include package-alexa.yaml
    apple_tv: !include package-apple-tv.yaml
    camera_entrance: !include package-camera-entrance.yaml
    camera_rome: !include package-camera-rome.yaml
    climate_smartir: !include package-climate-smartir.yaml
    met: !include package-met.yaml
    mikrotik: !include package-mikrotik.yaml
    mqtt_broker: !include package-mqtt-broker.yaml
    netatmo: !include package-netatmo.yaml
    sensor_smartmac: !include package-sensor-smartmac.yaml
    switch_broadlink_hub: !include package-switch-broadlink-hub.yaml
    switch_broadlink_sp3: !include package-switch-broadlink-sp3.yaml
    telegram: !include package-telegram.yaml
    xiaomi_vacuum: !include package-xiaomi-vacuum.yaml
    zha: !include package-zha.yaml

automation: !include automations.yaml
